title: Електријада
description: (Не)Званичан сајт организације одласка на Електријаду студената Факултета инжењерских наука универзитета у Крагујевцу
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
