name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the site with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./  # Path to your source directory
        destination: ./_site  # Path to the output directory
        future: false  # Whether to include posts scheduled for the future
        build_revision: ${{ github.sha }}
        verbose: false

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./_site  # Upload the build output

  deploy:
    runs-on: ubuntu-22.04
    needs: build  # Ensure deployment runs after the build job

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: github-pages

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_id: ${{ needs.build.outputs.artifact_id }}
        pages_build_version: ${{ github.sha }}
